### ISSUE TITLE
Missing global $db; and comment instead of comments

### ISSUE THREAD

**Issue by webchills** [lat9/edit_orders#111]
YOUR_ADMIN/includes/classes/editOrders.php

The new eoRecordStatusHistory should be
`public function eoRecordStatusHistory($oID, $message)
    {
    	global $db;
        if (function_exists('zen_update_orders_history')) {
            zen_update_orders_history($oID, $message);
        } else {
            $check_status = $db->Execute(
                "SELECT orders_status
                   FROM " . TABLE_ORDERS . "
                  WHERE orders_id = $oID
                  LIMIT 1"
            );
            $osh_sql = array(
                'orders_id' => $oID,
                'orders_status_id' => $check_status->fields['orders_status'],
                'date_added' => 'now()',
                'customer_notified' => -1,
                'comments' => $message
            );
            zen_db_perform(TABLE_ORDERS_STATUS_HISTORY, $osh_sql);
        }
    }

instead of

public function eoRecordStatusHistory($oID, $message)
    {
    	if (function_exists('zen_update_orders_history')) {
            zen_update_orders_history($oID, $message);
        } else {
            $check_status = $db->Execute(
                "SELECT orders_status
                   FROM " . TABLE_ORDERS . "
                  WHERE orders_id = $oID
                  LIMIT 1"
            );
            $osh_sql = array(
                'orders_id' => $oID,
                'orders_status_id' => $check_status->fields['orders_status'],
                'date_added' => 'now()',
                'customer_notified' => -1,
                'comment' => $message
            );
            zen_db_perform(TABLE_ORDERS_STATUS_HISTORY, $osh_sql);
        }
    }

**Comment by lat9** [comment]
Thanks for the report, @webchills; I'll get that updated shortly.
