### ISSUE TITLE
count() parentheses in wrong place

### ISSUE THREAD

**Issue by siliconforks** [lat9/edit_orders#115]
Under PHP 7.2, a warning `count(): Parameter must be an array or an object that implements Countable` is generated for this line:

https://github.com/lat9/edit_orders/blob/a866a00ae2ba2882ca9773d4e3fbac191d9bb5f0/YOUR_ADMIN/includes/functions/extra_functions/edit_orders_functions.php#L662

(Note: the line above is from version 4.3.5 but it appears that it still exists in the master branch.)

**Comment by lat9** [comment]
Thanks, @siliconforks!  Fix provided.
