### ISSUE TITLE
Additional separate tax line for the shipping fee while the tax rate is the same

### ISSUE THREAD

**Issue by webchills** [lat9/edit_orders#118]
Thanks for your hard work! You really brought this plugin to a new level!

While the calculations with beta10 are now fine (will test some special scenarios later this week) there is one thing which is strange for customers and shopowners

In an European store 95% of orders are orders like order 4 in the test store.
The tax for the shipping is in 95% of all cases the same as the normal tax for the product.
In Germany e.g. 19%
For other European countries there might be other tax rates but the principle is always the same.

A typical order with typical invoice will look like this.

![order4](https://user-images.githubusercontent.com/1009695/58385220-36825a80-7fed-11e9-9b48-31262b926070.jpg)

Zen Cart is showing the total tax amount (adding the product and the shipping tax which are both 19%) together in one line

It is not expected that the tax for the shipping is shown separately on an invoice.
But this is what is happening when you edit an order, e.g. change quantity to 2 and change the shipping fee like this:

![order4-1](https://user-images.githubusercontent.com/1009695/58385229-5285fc00-7fed-11e9-9b07-7084a1c84fb8.jpg)

After update two separate tax lines are added to the invoice. This will confuse both customers and shopowners:

![order4-2](https://user-images.githubusercontent.com/1009695/58385233-65003580-7fed-11e9-9bad-e348fdb3b517.jpg)

If the tax rate for product and shipping fee is the same their values should be added in one line  as it was in the original order.

**Comment by lat9** [comment]
@webchills, that's going to take some _more_ "thinking".  Would it suffice to combine those taxes into a **Sales Tax (19%)** (using a language-definition, with the tax-rate as supplied) if all products' tax-rates and the shipping tax-rate are the same?

**Comment by webchills** [comment]
It should just be like the normal handling in Zen Cart. Stores are used to have the taxes shown like this
![order5](https://user-images.githubusercontent.com/1009695/58385861-5585ea00-7ff7-11e9-8e76-7bfe2dd8bbd7.jpg)
In this case (Order 5 in test store) two products with different tax rates (19% and 7%)  were ordered. The tax rate for the shipping fee is 19% as well.
Zen Cart combines the two 19% values in one line. And the one 7% value in one line. The store owner (as well as fiscal authorities) is only interested in the sum of these tax rates. And that should be the way an edited order should look like as well. I don' t get the concept of an additional separate tax line for the shipping fee. No one is issuing invoices in such a way.

**Comment by lat9** [comment]
@webchills, that commit should correct the issue.
