### ISSUE TITLE
zc157: layout issues

### ISSUE THREAD

**Issue by lankeeyankee** [lat9/edit_orders#124]
On the latest version from today, with the latest zc from 157 branch, I get this layout on the edit orders page. Want to confirm this is seen elsewhere before addressing it on the local install.
![screen](https://user-images.githubusercontent.com/7685560/62000012-83d98180-b09b-11e9-9337-e9774682084a.jpg)

**Comment by lat9** [comment]
Thanks for the report.  I'll be interested in your updates!

**Comment by lankeeyankee** [comment]
Initial looks at admin/edit_orders doesn't have any spans that match the source, I am not sure if this is the general admin css being inserted due to a shared class name. Here's what the source looks like for the first line:

`<td class="a-r"><input type="number" name="shipping_tax" value="0.0000" class="amount" id="s-t" min="0" max="100" step="any" />&nbsp;<span class="alert">&nbsp;<span class="fieldRequired">* Required</span></span>&nbsp;%</td>`

**Comment by lat9** [comment]
Noting the [issue](https://github.com/zencart/zencart/issues/2668) raised for zc157.
