### ISSUE TITLE
Offer a products sort-order for the add-products products' dropdown

### ISSUE THREAD

**Issue by lat9** [lat9/edit_orders#138]
At step 2 of the add-products process, give the admin an opportunity to choose the sort-order to be applied to the products' dropdown, as noted in [this](https://www.zen-cart.com/showthread.php?225932-admin-function-zen_draw_products_pull_down-order-by-Admin-switch-or-selectable&p=1361989#post1361989) Zen Cart posting.

**Comment by proseLA** [comment]
hi cindy, 
i wanted to make you aware of some of the things that i do for my clients and that i'm trying to get into the ZC core.  it affects the add product function. while not specifically related to the sort, i thought it close enough that i would post it here (sorry if you would have preferred me opeing a new issue!).

one of my biggest issues has been the lack of consistency of keyword search and it being not that good.  in v158, there is a new function:

https://github.com/zencart/zencart/blob/06937378d8b0a56ac623bd33a5a4dfe46d66ee55/includes/functions/functions_search.php#L160-L201

i have already implemented this for my clients as it is an evolution of things i have done over the years.  in v157, it is already implemented for customer searchs and can be seen in this PR:

https://github.com/zencart/zencart/pull/3079

in edit orders, i think we can safely take this section of code:

https://github.com/lat9/edit_orders/blob/82f100bbd8b79dcc5c85b1a5c34a9d8aba6d662c/YOUR_ADMIN/edit_orders.php#L2130-L2136

and modify it as such

```
if (function_exists('zen_build_keyword_where_clause')) {
		        $keyword_search_fields = [
			        'pd.products_name',
			        'p.products_model',
			        'pd.products_description',
			        'p.products_id',
		        ];
		        $search = zen_build_keyword_where_clause($keyword_search_fields, trim($keywords));
	        } else {
		        $search = " WHERE (pd.products_name LIKE '%$keywords%'
                            OR pd.products_description LIKE '%$keywords%'
                            OR p.products_id = " . (int)$keywords . "
                            OR p.products_model LIKE '%$keywords%')";
	        }
	        $query .= $search . " ORDER BY p.products_id";
        }
```
this will preserve EO for use in older versions of ZC but provide the new functionality going forward.

i think users of EO, once they figure this out, will like this new search capability much more.  but i'm biased.

i can do a PR for you, if you are so inclined.

i am also invested in trying to get this keyword search into the `zen_draw_products_dropdown` but i'm waiting until some other refectors get merged.

best.
