### ISSUE TITLE
When Editing order its applying tax on shipping which is already taxed.

### ISSUE THREAD

**Issue by narenbambhaniya** [lat9/edit_orders#150]
When Editing order its applying tax on shipping which is already taxed.

**Comment by lat9** [comment]
You've not given me much to work with.  What version of EO (and Zen Cart)?  What shipping method?  What's the shipping method's configuration?  Are you displaying prices with tax?

**Comment by narenbambhaniya** [comment]
Editorder V4.5.0
Zencart 1.5.6c
Shipping Method : Zonerate

Configuration Below:
Zone Based Rates

Enable Zones Method
True

Calculation Method
Weight

Tax Class
VAT Taxable Goods

Tax Basis
Shipping

Sort Order
0

Skip Countries, use a comma separated list of the two character ISO country codes


Zone 1 Countries
GB,IM

Zone 1 Shipping Table
2:1.42,7:3.20,15:4.00,25:8.00,300:8.33,

Zone 1 Handling Fee
0

Handling Per Order or Per Box Zone 1 (when by weight)
Order

Zone 2 Countries
AT,BE,DE,FR,GL,IS,IE,IT,NO,DK,PL,ES,SE,CH,FI,PT,GR,NL,CY,GG,SW,HU,ML,

Zone 2 Shipping Table
3:7.90,5:8.90,7:9.20,9:10.75,20:12.60,50:15.00,100:25.00,300:35.00,500:37.00

Zone 2 Handling Fee
0

Handling Per Order or Per Box Zone 2 (when by weight)
Order

Zone 3 Countries
00

Zone 3 Shipping Table
3:7.60,5:8.60,7:10.50,9:11.50,20:12.60,50:15.00,100:25.00,300:35.00,500:37.00

Zone 3 Handling Fee
2.30

Handling Per Order or Per Box Zone 3 (when by weight)
Order



Configuration for TAX : 
Display Prices with Tax | true

**Comment by lat9** [comment]
OK, could you enable EO's debug and post a link to the generated output?

**Comment by narenbambhaniya** [comment]
https://www.narenbambhaniya.com/debug_edit_orders_63144.log

Here is the admin login info in case you want to check admin.(Its Test Site so you can modify anything)
https://www.narenbambhaniya.com/login.txt

**Comment by lat9** [comment]
@narenbambhaniya, I deleted that comment to give you a chance to remove those two files from your site.  I'm looking at the log you supplied right now.

**Comment by lat9** [comment]
I've successfully (unfortunately) replicated the issue locally (thanks for that EO debug)!  I should have a solution within a couple of days.

**Comment by lat9** [comment]
@narenbambhaniya, please validate that the correction provided by that just-pushed change corrects the issue that you reported.

**Comment by narenbambhaniya** [comment]
Yes. Working fine now. Thanks for providing fix.
