### ISSUE TITLE
buttons as gifs...

### ISSUE THREAD

**Issue by proseLA** [lat9/edit_orders#151]
hi cindy,
is this plugin still using gifs as opposed to bootstrap buttons?  see:

https://www.zen-cart.com/attachment.php?attachmentid=18878&d=1582558454

i would consider doing a pr for you if you are so inclined...

**Comment by lat9** [comment]
Until such time that EO leaves the zc155 branch in the dust, those buttons are needed since zc155 doesn't use bootstrap.
