### ISSUE TITLE
Values not displayed during product add of Option type PRODUCTS_OPTIONS_TYPE_SELECT_SBA

### ISSUE THREAD

**Issue by mc12345678** [lat9/edit_orders#160]
PR #40 added handling for editing the SBA specifically identified option name type `PRODUCTS_OPTIONS_TYPE_SELECT_SBA`; however, did not account for adding product that is both tracked by SBA where the option name type is set for SBA type option names.

**Comment by lat9** [comment]
Keeping open until v4.5.2 is released.
