### ISSUE TITLE
Admin Orders::Details button displays wonky on zc157

### ISSUE THREAD

**Issue by lat9** [lat9/edit_orders#173]
See [this](https://github.com/zencart/zencart/issues/3398) Zen Cart issue and [this](https://www.zen-cart.com/showthread.php?200407-Edit-Orders-v4-0-Support-Thread&p=1373875#post1373875) Zen Cart support-thread posting for additional information.

**Comment by proseLA** [comment]
hi cindy,
i think i resolved this issue by adding the following css:
`.fa-stack-1x, .fa-stack-2x {
    background-color: silver;
}
`
as to whether that styling works for you....
best.

**Comment by lat9** [comment]
As seen in that change just pushed, my preference was to use the built-in Zen Cart styling which hopefully won't change yet again.
