### ISSUE TITLE
minor suggestions...

### ISSUE THREAD

**Issue by proseLA** [lat9/edit_orders#174]
cindy,
i'm hoping i could get a couple of 'minor things' in here, prior to the next release.

i have modified fields in the orders_products table, so that when an item gets 'updated' for quantity, the deletion of the record and the recreation of the new one causes me to lose all of that data.  it would be GREAT if we could do the removal after the addition of the new record.  i have a very distinct feeling that would be too much of a big refactor, but i have to ask.

barring that, i could live with the addition of one line following this section of code:

https://github.com/lat9/edit_orders/blob/1f00f4c916eb89b507007e40159276987f05c60d/YOUR_ADMIN/edit_orders.php#L401-L426

here is the new line of code:

**`$new_product['old_orders_products_id'] = $orders_products_id;`**

which would do no damage that i can see, as i'm just adding an extra element to the new product array that i can use later in one of your observers.

speaking of observers, my other suggestion would be to add a new notifier event to the `eo_get_new_product` function.  and specifically prior to the return:

https://github.com/lat9/edit_orders/blob/1f00f4c916eb89b507007e40159276987f05c60d/YOUR_ADMIN/includes/functions/extra_functions/edit_orders_functions.php#L786-L788

i would like to be able to modify the `$retval` as i have custom way of naming products.

these mods would be most helpful to me during future updates.

i can do a PR if necessary.

**Comment by lat9** [comment]
I realize that the current remove/re-add processing can be a PITA (see #59), but there are already notifications that indicate that EO's about to remove a product:
https://github.com/lat9/edit_orders/blob/1f00f4c916eb89b507007e40159276987f05c60d/YOUR_ADMIN/includes/functions/extra_functions/edit_orders_functions.php#L1168
https://github.com/lat9/edit_orders/blob/1f00f4c916eb89b507007e40159276987f05c60d/YOUR_ADMIN/includes/functions/extra_functions/edit_orders_functions.php#L1216

Either of those would allow an observer to 'capture' the significant elements of the to-be-removed `orders_products` record for use in the (possibly) subsequent product-addition ... to 'put Humpty Dumpty back together again'.

The `eo_add_product_to_order` function issues a notification to which you can attach to make that ordered product 'whole':
https://github.com/lat9/edit_orders/blob/1f00f4c916eb89b507007e40159276987f05c60d/YOUR_ADMIN/includes/functions/extra_functions/edit_orders_functions.php#L1079

Note that the adding of a product can occur during an update (remove, then add) or a simple add-product action.  FWIW, this is the method I use within my [Products' Options' Stock Manager](https://vinosdefrutastropicales.com/index.php?main_page=product_info&cPath=2_7&products_id=46) plugin to manage the additions that it makes to an order's product records.

**Comment by proseLA** [comment]
> I realize that the current remove/re-add processing can be a PITA (see #59), but there are already notifications that indicate that EO's about to remove a product:
> https://github.com/lat9/edit_orders/blob/1f00f4c916eb89b507007e40159276987f05c60d/YOUR_ADMIN/includes/functions/extra_functions/edit_orders_functions.php#L1168
> 
ok, i can make that work.  thanks.

> speaking of observers, my other suggestion would be to add a new notifier event to the `eo_get_new_product` function. and specifically prior to the return:
> 
> https://github.com/lat9/edit_orders/blob/1f00f4c916eb89b507007e40159276987f05c60d/YOUR_ADMIN/includes/functions/extra_functions/edit_orders_functions.php#L786-L788
> 
> i would like to be able to modify the `$retval` as i have custom way of naming products.
>

what about the adding of an observer to modify the `$retval`?

**Comment by lat9** [comment]
That `$retval` modification is, as indicated above, not needed.  You can grab the 'current' orders_products information (saving in a class variable) during the remove operation and then use that on the notification during the product's add operation.

**Comment by proseLA** [comment]
i am sorry.  i need to pay better attention.  that change is not needed. 

i had mistakenly thought the `$retval` was used in a different place.  specifically when one adds a new item to an order here:

https://github.com/lat9/edit_orders/blob/1f00f4c916eb89b507007e40159276987f05c60d/YOUR_ADMIN/edit_orders.php#L2131-L2139

i see no easy answer for me not modifying this code short of changing the name to `zen_get_products_name($result->fields['products_id'])`.

thanks for the help.
