### ISSUE TITLE
Use 'role="table"' for screen readers

### ISSUE THREAD

**Issue by lat9** [lat9/edit_orders#177]
Preliminary change for #175 prior to address re-formatting.

**Comment by jage9** [comment]
Thanks for doing this. Sorry for not creating an associated issue with the PR; can do that next time. There are some more similar fixes to the product table among others that I'm testing now, so will submit that separately.

**Comment by lat9** [comment]
No worries.  I'm a little different in that I like to keep an issue open for an associated PR (or set of PRs) to jog my memory regarding whether or not there are changes for a plugin waiting to be released.  I appreciate your help.
