### ISSUE TITLE
Missing fields added in zc156 after update/product addition

### ISSUE THREAD

**Issue by lat9** [lat9/edit_orders#178]
See [this](https://www.zen-cart.com/showthread.php?200407-Edit-Orders-v4-0-Support-Thread&p=1374561#post1374561) Zen Cart support-thread posting for additional information.

**Comment by lat9** [comment]
Various fields added to the database schema for zc156 are not added when an order is updated (either via 'Update' or 'Add Product').  From the zc156's `zc_install` update script:
```
ALTER TABLE orders ADD order_weight FLOAT default NULL;

ALTER TABLE orders_products ADD products_weight float default NULL;
ALTER TABLE orders_products ADD products_virtual tinyint(1) default NULL;
ALTER TABLE orders_products ADD product_is_always_free_shipping tinyint(1) default NULL;
ALTER TABLE orders_products ADD products_quantity_order_min float default NULL;
ALTER TABLE orders_products ADD products_quantity_order_units float default NULL;
ALTER TABLE orders_products ADD products_quantity_order_max float default NULL;
ALTER TABLE orders_products ADD products_quantity_mixed tinyint(1) default NULL;
ALTER TABLE orders_products ADD products_mixed_discount_quantity tinyint(1) default NULL;

ALTER TABLE orders_products_download ADD products_attributes_id int(11) default NULL;
```

**Comment by proseLA** [comment]
hi cindy,
considering some impending changes, have you given any thought to perhaps changing the notifier here:

https://github.com/lat9/edit_orders/blob/1f00f4c916eb89b507007e40159276987f05c60d/YOUR_ADMIN/includes/functions/extra_functions/edit_orders_functions.php#L1079

the additional of the `$sql_data_array` to the notifier would be a big help, in that my little plugin (that addresses #59) would not need to be updated each time there are changes in the fields that are added.

best.
