### ISSUE TITLE
remove extra database query....

### ISSUE THREAD

**Issue by proseLA** [lat9/edit_orders#181]
https://github.com/lat9/edit_orders/blob/82f100bbd8b79dcc5c85b1a5c34a9d8aba6d662c/YOUR_ADMIN/includes/functions/extra_functions/edit_orders_functions.php#L582-L590

why couldn't line 586 just be:

`'name' => $country_info->fields['countries_name']`

**Comment by lat9** [comment]
Because that's future proofing for the possibility of having multi-lingual countries.
