### ISSUE TITLE
refactor for undefined price_calc_method

### ISSUE THREAD

**Issue by proseLA** [lat9/edit_orders#182]
i am not sure other the array_merge, why this section of code is within the `foreach` loop starting at line 368:

https://github.com/lat9/edit_orders/blob/82f100bbd8b79dcc5c85b1a5c34a9d8aba6d662c/YOUR_ADMIN/edit_orders.php#L453-L462

it can lead to a situation (seem out in the wild) where `$price_calc_method` is undefined here, as it is outside of the loop:

https://github.com/lat9/edit_orders/blob/82f100bbd8b79dcc5c85b1a5c34a9d8aba6d662c/YOUR_ADMIN/edit_orders.php#L498

**Comment by lat9** [comment]
Good point, the determination of the `$price_calc_method` should be done outside the loop and then used for each product being processed.
