### ISSUE TITLE
eliminate price input fields if price calc method is Auto or Autospecials

### ISSUE THREAD

**Issue by proseLA** [lat9/edit_orders#191]
i personally do not think it desirable to have input fields that do nothing.  i find it confusing and it confused me (until i looked closer and jostled my memory a bit).

i think it would be easy to either hide the input field and populate a message (or no message).  in fact, i have it done already but i wanted to know your thoughts.

**Comment by lat9** [comment]
Sounds like a great idea, @proseLA!
