### ISSUE TITLE
Button on order list is too large 

### ISSUE THREAD

**Issue by scottcwilson** [lat9/edit_orders#194]
If you use a class (or inline styling) that sets padding to 0, you can go from this: 

<img width="87" alt="ss1" src="https://user-images.githubusercontent.com/4391638/112754540-82680700-8faa-11eb-8654-6c3db6f2236a.png">

to this: 

<img width="98" alt="btn2" src="https://user-images.githubusercontent.com/4391638/112754545-898f1500-8faa-11eb-8dc9-643054102162.png">

**Comment by lat9** [comment]
I'm not a big fan (anymore) of inline styling and, since EO supports both zc156 and zc157, the classes available for styling are different.

I'll hold this open until such time as only zc157 and later are in the list of versions that EO supports.

**Comment by lat9** [comment]
Using `btn-sm` class for v4.7.0; see #224 for the change in EO's observer class.
