### ISSUE TITLE
request on tags

### ISSUE THREAD

**Issue by proseLA** [lat9/edit_orders#205]
hi cindy,
i'm now circling back around to releases and tags.  i learn more about git every day!

in #199, we had a brief conversation about branches and tags:

> > Since each release is tagged, e.g. the v4.5.7 release file-set can be found [here](https://github.com/lat9/edit_orders/tree/v4.5.7), I see no reason to keep release-specific branches.
> 
> concur. i should have looked at tags.
> 

in any event, i noticed my github fork did not contain the same tags that your repo did.  and the research that i did suggests that pushing all tags to my repo is not a good idea.  which lead me to the `--follow-tags` option, which requires that the tag be annotated as opposed to being unannotated.

far be it for me to make requests on your work flow, but it would be beneficial to me if when doing release tags you could annotate them.  this would allow my fork to stay up to sync with yours.

thoughts?

**Comment by lat9** [comment]
You are, as usual, ahead of me.  Where would I put that `--follow-tags` option?

**Comment by proseLA** [comment]
> You are, as usual, ahead of me. Where would I put that `--follow-tags` option?

you are too kind....

i set it up as a global config on the command line:
```
git config --global push.followTags true
```
i found this post of value:

https://stackoverflow.com/questions/5195859/how-do-you-push-a-tag-to-a-remote-repository-using-git?noredirect=1&lq=1

but i think the key thing is when creating a tag, you need to annotate it as a release, and then the `--follow-tags` option would come into play for those of us following along.

these 2 posts give a bit more information on them:

https://stackoverflow.com/questions/11514075/what-is-the-difference-between-an-annotated-and-unannotated-tag?noredirect=1&lq=1
https://stackoverflow.com/questions/4971746/why-should-i-care-about-lightweight-vs-annotated-tags

**Comment by lat9** [comment]
I'm confused (a normal thing).  I create the releases/tags using the github.com "Release" process -- shouldn't that wind up with the tag being annotated as a release?

**Comment by proseLA** [comment]
ok, i have done a bit more research.  it seems that going through github.com release process does NOT create annotated tags.  and that other people have talked about it for years:

https://stackoverflow.com/questions/29680947/is-there-any-way-to-create-an-annotated-tag-from-github

https://github.com/PHPMailer/PHPMailer/issues/752#issuecomment-226418384

https://github.com/knative/serving/issues/1869

i'm a command line guy when it comes to git and the github.  so i manage everything from the command line.

i'm also not that knowledgeable on tags, but i will play around with them.  i will see if i can tag a few of my releases on some of my code and how to annotate them using the github UI.

but its pretty clear the releases are not annotated.  from the command line in my local copy of edit_orders, if i were to type:
```
git cat-file -t v4.5.7
```
the response back is `commit`.  which is a non-annotated tag.  it would come back as `tag` if it were annotated.

coming back to my original comment:

> far be it for me to make requests on your work flow....

perhaps it is not possible from the github UI...  but i will look into it further.  it is not the that crucial...

but if someone else had some more knowledge to share on it, that would be great as well.
