### ISSUE TITLE
Label a release of 1.5.4? 

### ISSUE THREAD

**Issue by scottcwilson** [lat9/edit_orders#21]
Does it make sense at this point to label what's there as the 1.5.4 release so we can move on to 1.5.5 files?  There are a lot of fixes in this repo that are not in the Plugins version, aren't there?

**Comment by lat9** [comment]
Scott, I've got a couple of finishing touches to add before I create the "official" release.  I'm not sure what you mean by "move on to the 1.5.5 files".

**Comment by scottcwilson** [comment]
Oh, I just meant do the merges into 1.5.5 for modified core files.

**Comment by lat9** [comment]
I wasn't planning on providing merges for those files, only instructions for the additions for Zen Cart 1.5.5 and later.

This repo is, essentially, a fork of the "real" version maintained by @lhungil and I don't want to deviate too far from his roadmap.

**Comment by scottcwilson** [comment]
You already have a bunch of fixes he doesn't have.  Does it make sense to
update the Plugins version?

**Comment by lat9** [comment]
Yes, I'm going to update the version in the plugins area once I get this packaged up.
