### ISSUE TITLE
different handling for existing function zen_get_tax_locations

### ISSUE THREAD

**Issue by proseLA** [lat9/edit_orders#215]
is there a specific reason why the handling for this function is different from the rest of the `function_exists` checks?

https://github.com/lat9/edit_orders/blob/917318f80a716a0f7503853d7683c2cdbd50c9f8/YOUR_ADMIN/includes/functions/extra_functions/edit_orders_functions.php#L297-L302

in v158 this will generate this error as the admin side of v158 now includes all of the tax functions:
```
charmes: # grepp functions_taxes
includes/init_includes/init_general_funcs.php:26:require DIR_WS_FUNCTIONS . 'functions_taxes.php';
includes/functions/functions_taxes.php:3: * functions_taxes
admin/includes/init_includes/init_general_funcs.php:32:require DIR_FS_CATALOG . DIR_WS_FUNCTIONS . 'functions_taxes.php';
```

**Comment by lat9** [comment]
Most likely because that function in 154/155/156/157 didn't do what was needed.  I'll need to investigate the why of that code fragment.  EO's close to my next-up on zc158 compatibility.

**Comment by lat9** [comment]
I'll note, for instance, that the zc158 version of `zen_get_tax_locations` doesn't account for a 'virtual' order.  For that case, the tax-locations should be based on the 'billto' address.  Sigh.  Will you PR or should I?

**Comment by lat9** [comment]
... of course, neither did zc157.

**Comment by lat9** [comment]
FWIW, this has been changed for EO v4.7.0; see #224.
