### ISSUE TITLE
EO loses products_prid in orders_products table...

### ISSUE THREAD

**Issue by proseLA** [lat9/edit_orders#216]
here is the orders products table prior to doing anything:

![image](https://user-images.githubusercontent.com/1095136/196335166-2f5f9198-7f1c-4bd6-921c-0798780cd2e1.png)

now if i go into edit orders and click update, without doing anything, this is what my data now looks like:

![image](https://user-images.githubusercontent.com/1095136/196335679-fc77bfde-421f-459b-9d6c-3c6e1ab07200.png)

is this intended behavior?

this is on a site running 4.6.0.  i do not see anything in the notes to suggest that 4.6.1 or 4.6.2 has made any corrections to this issue.

**Comment by daphilli224** [comment]
The same behavior occurs for products_prid in orders_products_attributes table.
Dave
zc157c, php 8.0.22, eo 4.6.2
