### ISSUE TITLE
1.5.8 functions restructuring means `zen_get_tax_locations` is now visible in admin 

### ISSUE THREAD

**Issue by scottcwilson** [lat9/edit_orders#218]
The message `Pre-existing zen_get_tax_locations function detected.` is triggered in 1.5.8.

A few options are available (rename EO version of `zen_get_tax_locations`; call EO version in storefront function if called in admin context; move core function into a non-shared file, etc.)    Or it could be that this whole block (the check and redefinition) is no longer required for 1.5.8.

**Comment by JeffMash** [comment]
I don't know if this will break anything, but here is what I did (as an emergency in order to get the module to work for my needs).

1.  I completely removed the Lines 297 thru 343 in edit_orders_functions.php.   Specifically, this section was completely removed:

```
if (function_exists ('zen_get_tax_locations')) {
    trigger_error ('Pre-existing zen_get_tax_locations function detected.', E_USER_ERROR);
    exit ();
} else {
    function zen_get_tax_locations($store_country = -1, $store_zone = -1) {
        global $order;
        if (STORE_PRODUCT_TAX_BASIS == 'Store') {
            $GLOBALS['customer_country_id'] = STORE_COUNTRY;
            $GLOBALS['customer_zone_id'] = STORE_ZONE;
        } else {
            $_SESSION['customer_id'] = $order->customer['id'];

            if (STORE_PRODUCT_TAX_BASIS == 'Shipping') {
                global $eo;
                if ($eo->eoOrderIsVirtual ($GLOBALS['order'])) {
                    if (is_array ($GLOBALS['order']->billing['country'])) {
                        $GLOBALS['customer_country_id'] = $GLOBALS['order']->billing['country']['id'];
                    } else {
                        $GLOBALS['customer_country_id'] = zen_get_country_id ($GLOBALS['order']->billing['country']);
                    }
                    $GLOBALS['customer_zone_id'] = zen_get_zone_id ($GLOBALS['customer_country_id'], $GLOBALS['order']->billing['state']);
                } else {
                    if (is_array ($GLOBALS['order']->delivery['country'])) {
                        $GLOBALS['customer_country_id'] = $GLOBALS['order']->delivery['country']['id'];
                    } else {
                        $GLOBALS['customer_country_id'] = zen_get_country_id ($GLOBALS['order']->delivery['country']);
                    }
                    $GLOBALS['customer_zone_id'] = zen_get_zone_id ($GLOBALS['customer_country_id'], $GLOBALS['order']->delivery['state']);
                }
            } elseif (STORE_PRODUCT_TAX_BASIS == 'Billing') {
                if (is_array ($GLOBALS['order']->billing['country'])) {
                    $GLOBALS['customer_country_id'] = $GLOBALS['order']->billing['country']['id'];
                } else {
                    $GLOBALS['customer_country_id'] = zen_get_country_id ($GLOBALS['order']->billing['country']);
                }
                $GLOBALS['customer_zone_id'] = zen_get_zone_id ($GLOBALS['customer_country_id'], $GLOBALS['order']->billing['state']);
            }
        }
        $_SESSION['customer_country_id'] = $GLOBALS['customer_country_id'];
        $_SESSION['customer_zone_id'] = $GLOBALS['customer_zone_id'];
        
        return [
            'zone_id' => $GLOBALS['customer_zone_id'],
            'country_id' => $GLOBALS['customer_country_id']
        ];
    }
}
```

2.  I also added the following edit on Line 16 of eo_edit_action_display.php.   I put "lang." after the /modules/payment/ in order to account for the new naming convention for language files:

`require DIR_FS_CATALOG_LANGUAGES . $_SESSION['language'] . '/modules/payment/lang.' . $order->info['payment_module_code'] . '.php';`

After that, I was able to successfully edit my order to my needs.   Might not be the best "solution" which could possibly break something else in the plugin, but it worked for me.

- Jeff Mash

**Comment by JeffMash** [comment]
I agree, my solution is not a real "fix" since it's not loading the defines (but rather, it allows me to actually load the edit orders page to do what I need it to do).   I apologize if I was off-base in my original post, and I thank you for helping to educate me on the process of integration.

**Comment by lat9** [comment]
FWIW, I'm pretty sure that I've got this covered in the recently-pushed update (not totally ready yet) #224 for zc158 and later.
