### ISSUE TITLE
Add additional product type PRODUCTS_OPTIONS_TYPE_SELECT_SBA

### ISSUE THREAD

**Issue by mc12345678** [lat9/edit_orders#39]
Stock By Attributes includes a new product type
(PRODUCTS_OPTIONS_TYPE_SELECT_SBA) that
can be treated similar to the following ZC product types:
PRODUCTS_OPTIONS_TYPE_ATTRIBUTE_GRID
PRODUCTS_OPTIONS_TYPE_RADIO
PRODUCTS_OPTIONS_TYPE_SELECT

The product type is added to the proper tables and
areas as expected and described in the Edit Orders
forum.  

While there are ways to provide a more generic method 
of inclusion, the history of the plugin has been to more 
tightly control what has been made available to maintain
stability.

**Comment by lat9** [comment]
Reopening until it's released in an EO version.

**Comment by lat9** [comment]
@mc12345678, for the readme update, which version of SBA does this change encompass?

**Comment by mc12345678** [comment]
Somewhat of a difficult question to answer because technically potteryhouse in version 1.5.3 (August 24, 2014) properly incorporated the "expectation" of the product option type to be present and handled it correctly once the database was populated, but there were some logic errors potentially preventing the database from being populated (the lack of database population wouldn't affect the operation of the SBA related product with EO because product would not have been associated with the product option type).  It wasn't until November 17th, 2016 that code was added to specifically address/refine the interaction of SBA related product with EO.  

Then as to version... Well, I'm not really liking how the current version index is tracking alongside ZC instead of on its own, but have also seen so many version numbers applied to other variants (4.7 for example) that don't really want to mix things up even further.  It seems though like the next logical version number to apply to this "variant" is 1.5.5 even though it can be used with production releases of ZC 1.5.1-1.5.5.

So, truly, with the addition of the product option type PRODUCTS_OPTION_TYPE_SELECT_SBA, SBA version 1.5.3 and up will work with it, but there will be some "features" missing from the interaction that were not made available until November 17th, 2016.  The features are backwards compatible and provided as separate files that could be applied to a SBA 1.5.3 install.

**Comment by lat9** [comment]
I'm just trying to find a phrase to accompany this change in the EO readme, so that people combining the two have a clue as to which version of SBA they need.

Also, need to update the base edit_orders.php module to make sure that the `PRODUCTS_OPTIONS_TYPE_SELECT_SBA' definition is created if it doesn't already exist.

**Comment by mc12345678** [comment]
Understand the goal of the instruction.  Had this characteristic been reviewed more earlier on, the current functionality likely would have already existed, but all-in-all, once the code is included in EO, it would be considered functional with SBA 1.5.3 and above.  Any added features by more recent versions of SBA are not the responsibility of EO to report.

I had considered adding a similar "check" for the existence of the constant, but within the "tools" that are readily available the consequence of providing a string of text instead of a number for the "unknown" option type if it were to find its way into the output somehow was not visible. Adding the applicable code to the commit to be able to address the request.

**Comment by mc12345678** [comment]
Thank you!

**Comment by lat9** [comment]
No problem!  I just submitted to the Zen Cart plugins, so the update should be available for download there next weekend.
