### ISSUE TITLE
Remove orders.php integration with Ty Package Tracker

### ISSUE THREAD

**Issue by lat9** [lat9/edit_orders#42]
Ty Package Tracker is separately managed and has been updated since its integration with EO.  To reduce the EO installation complexity, that integration will be removed.

**Comment by lat9** [comment]
@jeking928, are there any notifiers that I could include in the EO update that will make the TyPT integration more "drop in"?

**Comment by jeking928** [comment]
@lat9 My updates to TY were only updates to maintain compatibility. I think the answer is no, but I'm not really qualified to answer.  :-)

**Comment by lat9** [comment]
Thanks, @jeking928, I'll review those changes and see if there's any "easy" way to provide those integration hooks.

**Comment by lat9** [comment]
As with that last title change, my main motivation in the de-coupling of the EO distribution and TyPT are the changes required to the core-file `/YOUR_ADMIN/orders.php` to enable EO to be independent of the underlying Zen Cart processing.

I'll be keeping the TyPT integration within the `/YOUR_ADMIN/edit_orders.php` file, at least for this go-round.

**Comment by jeking928** [comment]
I think de-coupling is the right way to go. It *really* complicates things! And TyPT isn't that hard to install on it's own. Just my $0.02.

**Comment by lat9** [comment]
Jim, I haven't peeked at the TyPT installation in a while; does it provide pre-integration with both orders.php and edit_orders.php?

**Comment by jeking928** [comment]
It does with orders.php but not edit_orders.php. Unless I'm missing something, there isn't much of a need for it to integrate with Edit Orders. It did with Super Orders to allow both to be used from the same page, but again, installing each plugin individually can be done.

**Comment by lat9** [comment]
Removed the v4.2.0 milestone, to keep this issue "on-focus" for the next round of EO changes.

**Comment by lat9** [comment]
Never mind on the above.  Since the default orders.php **has** been changed to use the Zen Cart 1.5.5d version as the change basis, the TyPT changes will be removed from the `orders.php` processing but left in `edit_orders.php` for the time being.
