### ISSUE TITLE
Shipping and tax

### ISSUE THREAD

**Issue by syntaxerror** [lat9/edit_orders#60]
In most stores in the Nordics, shipping etc. is displayed including tax in order totals.

But in Edit Orders it seems to be handled as it's exclusive tax, so extra tax is added for shipping on recalculation. This means the store admin would have to remove the tax from the shipping price before updating the order, else the tax total will be incorrect.

Tested on ZC 1.5.5e and Table shipping.
Tax base is shipping (still, same if set to store).
PHP 5.6

**Comment by lat9** [comment]
I'll need some time to investigate further.

**Comment by lat9** [comment]
Like I've asked in that other issue, which version of EO are you using?  Did you try this with the "Recalculate Totals" box checked?

**Comment by syntaxerror** [comment]
Yes, the problem is deeper than that.

**Comment by lat9** [comment]
Just so I'm clear, you're using EO 4.3.0 and have tried also using the "Recalculate Totals" box checked?  Have you made any changes to the default EO configuration settings?

Your store uses "Display prices with taxes" and "Display prices with taxes, admin" set to true and using the built-in table-rate shipping with the shipping taxed, correct?

I'm just trying to gather information that I can use to replicate the issue.

**Comment by syntaxerror** [comment]
> Just so I'm clear, you're using EO 4.3.0 and have tried also using the "Recalculate Totals" box checked?
Yes

> Have you made any changes to the default EO configuration settings?
No

> Your store uses "Display prices with taxes" and "Display prices with taxes, admin" set to true 
Yes

> and using the built-in table-rate shipping with the shipping taxed, correct?
Yes

**Comment by lat9** [comment]
I've replicated the issue on my local test-bed and _should_ have a solution shortly.

**Comment by lat9** [comment]
Those changes (see that previous commit) should do the trick.  The update ensures that any shipping tax is removed from the shipping cost and overall tax values when a store "Displays prices with tax".

**Comment by lat9** [comment]
@syntaxerror, could you validate that the changes I provided do, in fact, correct the issue you reported?

**Comment by syntaxerror** [comment]
Will do, next year ... out of time ...

**Comment by lat9** [comment]
OK, I'll hold the EO update until your verification.

**Comment by syntaxerror** [comment]
I created a test copy of the store, and toold the store admin to test Order Edit **a lot**, and the responce is that it seems to be good. :)

And for the record, I used the master branch (4.3.1-beta3) from yesterday.

**Comment by lat9** [comment]
Thanks, @syntaxerror, that third-party testing is much appreciated!

**Comment by lat9** [comment]
I'm re-opening this until the change is included in a released version of EO, for trackability.
