### ISSUE TITLE
incorrect  total price in attributes when first added, before clicking update

### ISSUE THREAD

**Issue by lankeeyankee** [lat9/edit_orders#79]
If you add an item with attributes that are either on sale/special or for some other reason are priced by 4 decimals in the DB and add enough quantity it will at first display an incorrect total price until the update button is clicked.

Example: item is 5.99 priced by attribute, apply a 5% sale, the new price is $5.6905 which is correctly displayed as $5.69, add 10 through the add product funtion and the total price shows  as $56.91 when you come back to the main page. Once you click update it correctly changes the total to $56.90. 

Just a small thing that can be confusing as well as cause errors. If you are adding an order comment saying what is added/subtracted/changed plus the total you might be off from the actual total.

**Comment by lat9** [comment]
That's a "known issue" with the current Edit Orders v4 implementation.  I'm working on a 5.0.0 release that should correct this.

**Comment by lankeeyankee** [comment]
Great, thanks!!

**Comment by lat9** [comment]
Just validated that the various changed made for EO 4.4.0 (currently on the pricing_fixups branch) in the "rounding" area appear to have corrected this issue.

**Comment by lankeeyankee** [comment]
Fantastic, thanks so much!!
