### ISSUE TITLE
error in doc for interaction/attribute tab

### ISSUE THREAD

**Issue by lankeeyankee** [lat9/edit_orders#80]
I believe this line in the doc section for attributes:

`$options_order_by= ' order by LPAD(popt.products_options_sort_order,11,"0", popt.products_options_name)';`

should maybe be 

`$options_order_by= ' order by LPAD(popt.products_options_sort_order,11, popt.products_options_name)';`

Removing "0", 

I was getting a fatal error with the code as-is in the doc.

**Comment by lat9** [comment]
Thanks for the report.  That line should actually read

`$options_order_by= ' order by LPAD(popt.products_options_sort_order,11,"0"), popt.products_options_name';`

That change moved the closing parentheses to after the "0".

**Comment by lat9** [comment]
I normally keep issues open until the associated changes have been released.  It helps me keep "focus".

**Comment by lankeeyankee** [comment]
sorry!
