### ISSUE TITLE
v5.0.0: Error when adding a product at step 5

### ISSUE THREAD

**Issue by webchills** [lat9/edit_orders#83]
Add a product to an order
This calls line 126 in admin/edit_orders.php
// Get Order Info
$order = $eo->eoGetOrderInfo();
This is nowhere defined, so you get
Call to undefined method editOrders::eoGetOrderInfo()

**Comment by lat9** [comment]
This occurs down the 'add-a-product' path, which (like the attributes' pricing) hasn't yet been completed.
