### ISSUE TITLE
v5.0.0-beta2: Changing shipping fee or shipping method does not have any effect

### ISSUE THREAD

**Issue by webchills** [lat9/edit_orders#85]
Edit an order
Leave the selected shipping method Flat Rate
Change the amount of its shipping fee to an other value
Click the update button
You get the message "Success: Order has been successfully updated"
But nothing has changed

Edit an order
Change the selected shipping method from Flat Rate to Per Item
Enter any description for Per Item and enter an amount
Click the update button
You get the message "Success: Order has been successfully updated"
But nothing has changed

**Comment by lat9** [comment]
Yep, that beta2 is in "bad shape".  I'm working to get it updated, but it's not worth your time checking anything out until I get that finished.

I realize that it's taking forever ...
