### ISSUE TITLE
Correct rounding issues

### ISSUE THREAD

**Issue by lat9** [lat9/edit_orders#95]
Various locations in the update/add-product processing that need updates to correct tax-inc/tax-exc calculations.  I'm "hoping" that these updates will also address #61 and #79.

**Comment by lat9** [comment]
@webchills, could you give this branch (https://github.com/lat9/edit_orders/tree/pricing_fixups) a try to see if that processing corrects the rounding issues you've experienced?

**Comment by lat9** [comment]
When using the above branch, please check/edit your `/admin/includes/functions/functions_taxes.php` to ensure that the unwanted pre-rounding (https://www.zen-cart.com/showthread.php?224957-Unwanted-pre-rounding-in-admin-s-zen_add_tax-function) functionality has been removed.

**Comment by webchills** [comment]
Tried 4.3.6 beta3

in  ADMIN/includes/functions/general.php changed to

function zen_add_tax($price, $tax) {
    global $currencies;

    if (DISPLAY_PRICE_WITH_TAX_ADMIN == 'true') {
      return ($price + zen_calculate_tax($price, $tax));
    } else {
      return $price;
    }
  }

Sub-Total and Total are wrong when editing an order

Product with
Price Net: 35
Tax Rate: 10%
Price Gross: 38.50

Shipping Fee: 5.00
No Tax for shipping Fee

Order 1 piece of this product

Result:
Sub-Total: 38.50
Shipping:  5.00
included tax (10%): 3.50
Total: 43.50


Edit with Edit Orders 4.3.6 beta 3
Setting: Reset Totals on Update: On
(same behaviour with this setting to Off)
Product price calculation: Auto
Change quantity to 2

Result:

Sub - Total: 84.70
wrong, should be 77.00
Shipping: 5.00
Old entry included tax (10%) remains: 3.50
Additional entry included tax is added: 7.00
Total: 89.70
wrong should be 82

**Comment by lat9** [comment]
Thanks, @webchills.  I've got the rounding worked out for prices displayed without tax and this (and your other posting) will nelp me hone in on the solution for prices displayed with tax.

**Comment by lat9** [comment]
Here's the link to that Zen Cart support-thread posting: https://www.zen-cart.com/showthread.php?200407-Edit-Orders-v4-0-Support-Thread&p=1347215#post1347215

**Comment by lat9** [comment]
Just updated `/admin/includes/functions/extra_functions/edit_orders_functions.php`, removing an unwanted tax-addition when the store displays prices with tax.

I've verified the operation with the problematic order you posted above and with the one posted on the Zen Cart forums.

**_Note:_**  The results calculated by EO for the Zen Cart posting come back with a penny-less difference of the tax and total values, but I believe that EO's calculations are correct:

```
29.90 * .19 = 4.773959 ... rounded = 4.77
4.16 * .19 = .7904 ... rounded = .79
```

Total tax should be 4.77 + .79 = 5.56, not 5.57.

**Comment by webchills** [comment]
Thanks for the fix, I applied it and tested again with my example from the forum thread. Result is now correct! When editing the order the price for the shipping fee is shown wrong as 5.89 (EO seems to take the gross price of 4.95 including 19% tax and then adds 19% again). So users have to change this value to the net shipping fee of 4.16 before updating the order. This might confuse users. Will test some other scenarios in the next days.

**Comment by lat9** [comment]
Good point, @webchills.  Which would be the best/easiest approach for stores that `DISPLAY_PRICES_WITH_TAX`: To display (and assume entry of) prices with tax or without?

@Zen4All, do you have an opinion on the display?

**Comment by webchills** [comment]
As anything else is shown with tax here it would make sense to display and assume entry of prices with tax. Concerning the shipping fee: In most cases the shipping fee will remain the same when an order is edited. The field should show the current shipping fee with tax (4.95 in our example), so no further editing is required at all. Showing any other value here is confusing.

**Comment by lat9** [comment]
@webchills, that commit just pushed does some "restructuring" on EO's main display page when a store displays prices with tax, including both net and gross amounts for product and shipping prices.

There's a bit of jQuery now that (like the products' definition) swizzles the net/gross values when one of those fields or their associated tax-rate changes.  I believe that this corrects the unwanted shipping rate tax-compounding.

**Comment by lat9** [comment]
Unfortunately, those changes were necessary but insufficient.  If an order's shipping tax is to be overridden, there needs to be some record of the tax-rate applied to the shipping that's recorded as part of the order.

**Comment by lat9** [comment]
Noting here that the next version of Edit Orders will be 4.4.0, due to the changes needed to properly track the shipping tax-rate for the order.  There will most likely remain underlying issues with other order-total modules that apply tax to their values, but that's outside the scope of this update.

**Comment by lat9** [comment]
@webchills, I've validated the scenario reported in this issue with the current EO 4.4.0 (in the pricing_fixups branch) and it's looking good to me!  I'd appreciate verification from you that _**you**_ believe that the issue's been resolved.

**Comment by webchills** [comment]
The new input fields are fine as well as the new field in the orders table to store the shipping fee tax rate. 
The functionality is still broken though.
Change the shipping fee of an order with EO.
Entering the net value shows the correct gross value in the appropiate field.
But when you click on Update, always the net value is saved which is wrong.
As a result the calculated tax is wrong as well.

**Comment by lat9** [comment]
@webchills, as you can tell, I've done limited testing for stores that display prices with tax.  I'll get that checked out later today/tomorrow.

**Comment by lat9** [comment]
@webchills, I'm not seeing what you're seeing.

Using the scenario you'd posted initially (the 35.00-net product (10% tax)  w/ 5.00 shipping, untaxed):

- I initially placed the order (Sub-total: 38.50, Shipping 5.00, Tax: 3.50, Total: 43.50).
- Updated the order, updating the product qty to 2 (Sub-total: 77.00, Shipping: 5.00, Tax: 7.00, Total: 82.00)
- Updated the order, updating the shipping cost (net/gross) to 10.00 (Sub-Total: 77.00, Shipping: 10.00, Tax: 7.00, Total: 87.00)

Running zc156 (current zc156b changes) on PHP 7.1.4.

What are you doing differently?

**Comment by webchills** [comment]
Zen Cart 1.5.5f on PHP 7.1.29
Existing Order looks like
![shipping-eo-1](https://user-images.githubusercontent.com/1009695/58026127-1696f680-7b16-11e9-8422-91c8858d965b.jpg)
Edit the shipping fee to 100 net > 119 gross gets correctly displayed:
![shipping-eo-2](https://user-images.githubusercontent.com/1009695/58026208-3f1ef080-7b16-11e9-947e-01171ec4e611.jpg)
Click update and you will see that the ne price is stored which is wrong:
![shipping-eo-3](https://user-images.githubusercontent.com/1009695/58026254-578f0b00-7b16-11e9-8b2f-0d86e340d422.jpg)
I will provide you admin access to the test store via email, so you can have a closer look at its configuration

**Comment by lat9** [comment]
@webchills, v4.4.0-beta8 is now available for testing.  I'm pretty sure that those changes will correct those shipping-related calculations.

**Comment by webchills** [comment]
Sorry to be such a pain, but with beta-8 the shipping fee is always set to 0 after clicking update no matter what you enter before (see test store)

**Comment by lat9** [comment]
Hmm, I'm not seeing that behavior on my test setup where  I've installed v4.4.0-beta8 on a zc155f test store.  Are you sure that you copied all the updates?  Make sure that you've got EO's admin observer class updated.

**Comment by lat9** [comment]
Oops!  Forgot to update the readme's installation section (Required Notifiers) to identify that zc155-based stores will need to update `/includes/modules/order_total/ot_shipping.php` to include a notification that's built into zc156.

**Comment by lat9** [comment]
Also found (thanks @webchills, for the test-site access) that the `Reset totals prior to update` is what is now "getting in the way".  The pricing restructuring/corrections for v4.4.0 have been developed and tested with that checkbox _unticked_ and it's no longer needed or wanted!

I'll get a beta9 going that removes that setting.
