### ISSUE TITLE
Can't 'update' an order with automatic pricing, using specials pricing.

### ISSUE THREAD

**Issue by scottcwilson** [lat9/edit_orders#99]
I believe this value should be `true`.  Otherwise the updated price will fail to reflect the fact that the product is on special.  (Arguably this should be switchable via a checkbox.) 

https://github.com/lat9/edit_orders/blob/34bb4ce78e855a4de253b1e18350c51c5b26fcc7/YOUR_ADMIN/edit_orders.php#L405

**Comment by lat9** [comment]
Let me think through the user interface.  There's already a checkbox during the add-product path, but a checkbox tick on a **_Use Specials_** checkbox during update will _only have effect_ when the update is being performed using _automatic pricing_.

**Comment by scottcwilson** [comment]
It could be that `true` should be hardcoded with no need for switchability.  But if a checkbox were provided, I would say put it next to the update button.

**Comment by lat9** [comment]
I'll need to consider that, since hard-coding that value would result in a behavioral change.  As much as I don't like all the 'tick' boxes, I'd rather that direction to allow downward-compatible processing (noting that the compatible processing might not be what's wanted!).
